name: Destroy infraestructure Terraform AWS

on:
    workflow_dispatch: # To enable a workflow to be triggered manually
#      inputs:
#
#        instance_type:
#          description: 'Colocar el tipo de instancia a destruir del cluster de minikube' #Se puede poner condiciones ejemplo: diferente a t2.micro
#          required: true

defaults:
  run:
    working-directory: ./Terraform_cicd

jobs:
    destroy:
        name: Destroy AWS infraestructure
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-west-2
    
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform init
              id: init
              run: terraform init
              #env:
                #TF_VAR_instance_type: terraform state show module.minikube.aws_instance.minikube_server | grep "instance_type" | awk '{print $3}'

            #- name: Testing terraform show
            #  run: terraform state show module.minikube.aws_instance.minikube_server | grep "instance_type" | awk '{print $3}'

            - name: Terraform Destroy
              id: destroy
              run: terraform destroy -auto-approve
              env:
                TF_VAR_instance_type: terraform state show module.minikube.aws_instance.minikube_server | grep "instance_type" | awk '{print $3}'


# El error de los variables es posible que se solucione juntando un archivo de variables donde se declar el valor





