name: Destroy infraestructure Terraform AWS

on:
    workflow_dispatch:
      inputs:

        instance_type:
          description: "Colocar el type de instancia a destruir"
          required: false

defaults:
  run:
    working-directory: ./Terraform_cicd

env:
  TF_VAR_instance_type: "${{ github.event.inputs.instance_type }}"

jobs:
    destroy:
        name: Destroy AWS infraestructure
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4
    
            - name: load & test action
              uses: ./.github/actions/node-ci

            - name: Terraform Destroy
              id: destroy
              run: terraform destroy -auto-approve

# El error de los variables es posible que se solucione juntando un archivo de variables donde se declar el valor





