name: Destroy infraestructure Terraform AWS

on:
    workflow_dispatch:

defaults:
  run:
    working-directory: ./Terraform_cicd

jobs:
    destroy:
        name: Destroy AWS infraestructure
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4
    
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-west-2
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
                #with:
                  #terraform_version: "1.7.4"

            - name: Terraform init
              id: init
              run: terraform init

            - name: Terraform Destroy
              id: destroy
              run: terraform destroy -auto-approve

# El error de los variables es posible que se solucione juntando un archivo de variables donde se declar el valor





